from lastalConfig import *

lastalDict={"-D":alignExpect,
"-E":maxEG2,
"-r":matchScore,
"-q":misMatch,
"-p":scoreMatrix,
"-a":gapExistCost,
"-b":gapExtendCost,
"-A":insertExistCost,
"-B":insertExtendCost,
"-c":afflineGap,
"-x":maxScoreDropGap,
"-y":maxScoreDropGapless,
"-z":maxScoreDropGapFinal,
"-d":minScoreGap,
"-e":minAlignScore,
"-m":multiplicity,
"-l":minInitMatchLength,
"-L":maxInitMatchLength,
"-k":searchStep,
"-W":minQuerySize,
"-s":queryStrand,
"-S":dnaStrand,
"-K":numOverlapQuery,
"-C":numOverlapExtend,
"-P":numThreads,
"-i":batchSize,
"-M":minDiffAligns,
"-T":alignType,
"-n":alignPerQueryPosition,
"-R":repeatHandling,
"-u":treatLower,
"-w":timeKludge,
"-G":alternateCode,
"-t":scoreToLikelihood,
"-g":gammaVal,
"-j":output,
"-Q":qualityTreatment}

for k in lastalDict.keys():
    if lastalDict[k]:
        print k, lastalDict[k],
